services:
  - type: web
    name: cs-jerusalem
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask db upgrade
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        value: admin@csjerusalem.cd
      - key: ADMIN_MOT_DE_PASSE
        sync: false
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "1"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: "CS Jérusalem <no-reply@csjerusalem.cd>"
