"""discipline module

Revision ID: ac61c9f74251
Revises: d17c759e822d
Create Date: 2026-08-14 17:51:21.089897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac61c9f74251'
down_revision = 'd17c759e822d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('parent_profile_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure', sa.Time(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['parent_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinary_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinary_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['disciplinary_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplinary_actions')
    op.drop_table('disciplinary_incidents')
    op.drop_table('convocations')
    # ### end Alembic commands ###
