"""admissions module

Revision ID: d17c759e822d
Revises: 6fcb3a514f04
Create Date: 2026-08-13 23:57:42.537423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17c759e822d'
down_revision = '6fcb3a514f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('postnom', sa.String(length=120), nullable=True),
    sa.Column('prenom', sa.String(length=120), nullable=True),
    sa.Column('sexe', sa.String(length=1), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=150), nullable=True),
    sa.Column('nationalite', sa.String(length=80), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('ancienne_ecole', sa.String(length=200), nullable=True),
    sa.Column('classe_demandee_id', sa.Integer(), nullable=True),
    sa.Column('parent_nom', sa.String(length=120), nullable=False),
    sa.Column('parent_telephone', sa.String(length=30), nullable=False),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('parent_adresse', sa.String(length=300), nullable=True),
    sa.Column('parent_relation', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resulting_student_profile_id', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classe_demandee_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resulting_student_profile_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('documents')
    # ### end Alembic commands ###
